# -*- coding: utf-8 -*-
"""p1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13q87Y7ogw9JlwOoVQnphZ77oS9ZEytOh
"""

# nama file p1.py 
# Isikan email anda dan copy semua cell code yang dengan komentar #Graded

# untuk revisi dan resubmisi sebelum deadline
# silakan di resubmit dengan nilai variable priority yang lebih besar dari
# nilai priority submisi sebelumnya
# JIKA TIDAK ADA VARIABLE priority DIANGGAP priority=0
priority = 1

#netacad email cth: 'abcd@gmail.com'
email='prasastiasaliha@gmail.com'
 
# copy-paste semua #Graded cells YANG SUDAH ANDA KERJAKAN di bawah ini

def letter_catalog(items,letter='A'):
  buah=[]
  for i in items:
      if i[0] == letter:
          buah.append(i)
  return buah

def counter_item(items):
  
  value = {i:items.count(i) for i in items}
  return value

  # dua variable berikut jangan diubah
fruits = ['Apple','Avocado','Banana','Blackberries','Blueberries','Cherries','Date Fruit','Grapes','Guava','Jackfruit','Kiwifruit']
prices = [6,5,3,10,12,7,14,15,8,7,9]

# list buah
chart =['Apple', 'Banana', 'Cherries', 'Avocado', 'Avocado', 'Cherries', 'Avocado', 'Blackberries', 'Avocado', 'Cherries']

# MULAI KODEMU DI SINI
fruit_price = {}
for i in fruits:
  for value in prices:
    fruit_price[i] = value
    prices.remove(value)
    break

def total_price(dcounter,fprice):
   data=[]
   for i in dcounter.keys() & fprice.keys():
     total =dcounter[i]* fprice[i]
     data.append(total)
   jumlah = sum(data)
   return jumlah

def discounted_price(total,discount,minprice=100):
  global harga
  disc = discount/100*total
  harga = total - disc
  if(total >= minprice):
    return harga
  else:
    harga = total
    return harga

def print_summary(items,fprice):
  a = counter_item(items)
  b = total_price(a,fprice)
  for i in sorted(a.keys()) :
    total= a[i] * fprice[i]
    print(a[i],i, total, end='\n')
  print('total :',b)
  print('discount :', harga)

letter_catalog(['Apple','Avocado','Banana','Blackberries','Blueberries','Cherries'],letter='A')
counter_item(['Apple','Apple','Apple','Blueberries','Blueberries','Blueberries'])
total_price(counter_item(chart),fruit_price)
discounted_price(total_price(counter_item(chart),fruit_price),10,minprice=100)
print_summary(chart,fruit_price)